TrendyShop/Controllers/StatisticsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using TrendyShop.Data;
using TrendyShop.Models;
using TrendyShop.Utility;
using TrendyShop.ViewModels;
//using Syncfusion.XlsIO;                              PAQUETE!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
using System.IO;

namespace TrendyShop.Controllers
{
    [Authorize(Roles = SD.AdminEndUser)]
    public class StatisticsController : Controller
    {
        private DataContext context;


        public StatisticsController(DataContext ctx)
        {
            context = ctx;
        }

        static List<YearStatisticsViewModel> allYearStatisitics;

        public IActionResult Index()
        {

            var lodgings = Statics.GetLodgings(context).GroupBy(l => l.Date.Year);
            List<int> years = new List<int>();

            foreach (var item in lodgings)
            {
                years.Add(item.Key);
            }
            years.Sort();

            allYearStatisitics = new List<YearStatisticsViewModel>();
            foreach (var year in years)
            {
                allYearStatisitics.Add(GetYearStatistics(year, context));
            }

            return View(allYearStatisitics);
        }


        //public IActionResult ExportToExcel(int year, YearStatisticsViewModel yearSs)
        //{
        //    List<YearStatistics> yearStatisticsTable = new List<YearStatistics>();
        //    YearStatisticsViewModel yearS = allYearStatisitics.Find(y => y.Year == year);

        //    for (int i = 1; i < 13; i++)
        //    {
        //        YearStatistics row = new YearStatistics
        //        {
        //            Month = yearS.Months[i],
        //            Lodgings = yearS.LodgingsPerMonth[0],
        //            DoubleLodgings = yearS.DoubleLodgingsPerMonth[i],
        //            DailyLodgings = yearS.DailyLodgingsPerMonth[i],
        //            RentIncome = yearS.RentIncomePerMoth[i],
        //            ConsumptionIncome = yearS.ConsumptionIncomePerMonth[i],
        //            ConsumptionProfit = yearS.ConsumptionProfitPerMonth[i],
        //            DamageIncome = yearS.DamageIncomePerMoth[i],
        //            GrossIncome = yearS.GrossIncomePerMonth[i],
        //            Salary = yearS.SalaryPerMoth[i],
        //            HouseExpenses = yearS.HouseExpensesPerMoth[i],
        //        };
        //        yearStatisticsTable.Add(row);
        //    }

        //    using (ExcelEngine excelEngine = new ExcelEngine())
        //    {
        //        IApplication application = excelEngine.Excel;
        //        application.DefaultVersion = ExcelVersion.Excel2013;

        //        //Create a new workbook
        //        IWorkbook workbook = application.Workbooks.Create(1);
        //        IWorksheet sheet = workbook.Worksheets[0];


        //        sheet.ImportData(yearStatisticsTable, 2, 1, false);

        //        sheet.Range["A1"].Text = year.ToString();
        //        sheet.Range["B1"].Text = "Reservas";
        //        sheet.Range["C1"].Text = "Reservas Dobles";
        //        sheet.Range["D1"].Text = "Reservas Diarias";
        //        sheet.Range["E1"].Text = "Ingreso x Renta";
        //        sheet.Range["F1"].Text = "Consumo";
        //        sheet.Range["G1"].Text = "Ganacia x Consumo";
        //        sheet.Range["H1"].Text = "Ingreso x Daños";
        //        sheet.Range["I1"].Text = "Ingreso Bruto";
        //        sheet.Range["J1"].Text = "Salario";
        //        sheet.Range["K1"].Text = "Otros Gastos";

        //        //Saving
        //        string name = "Estadísticas" + " " + year.ToString() + ".xlsx";
        //        string path = @"C:\Users\Sandra\Desktop\Mi Carreta  actual\" + name;

        //        FileStream file = new FileStream(path, FileMode.Create, FileAccess.ReadWrite);
        //        workbook.SaveAs(file);

        //        file.Dispose();
        //    }

        //    return RedirectToAction("Index", "Statistics");
        //}


        static YearStatisticsViewModel GetYearStatistics(int year, DataContext context)
        {
            int[] m = new int[] { 1, 3, 5, 7, 8, 10, 12 };

            int[] lodgingsPerMonth = new int[13];
            string[] dailyLodgingsPerMonth = new string[13];
            int[] doubleLodgingsPerMonth = new int[13];
            float[] consumptionIncomePerMonth = new float[13];
            float[] ConsumptionProfitPerMonth = new float[13];
            float[] salaryPerMonth = new float[13];
            float[] allHouseExpensesPerMonth = new float[13];
            float[] rentIncomePerMonth = new float[13];
            float[] damageIncomePerMonth = new float[13];
            float[] grossIncomePerMonth = new float[13];

            //To round
            string[] consumptionIncomePerMonthStr = new string[13];
            string[] ConsumptionProfitPerMonthStr = new string[13];
            string[] salaryPerMonthStr = new string[13];
            string[] allHouseExpensesPerMonthStr = new string[13];
            string[] rentIncomePerMonthStr = new string[13];
            string[] damageIncomePerMonthStr = new string[13];
            string[] grossIncomePerMonthStr = new string[13];


            for (int i = 1; i < lodgingsPerMonth.Length; i++)
            {
                DateTime initialDate = new DateTime(year, i, 1);
                DateTime finalDate;

                if (m.Contains(i))
                {
                    finalDate = new DateTime(year, i, 31);
                }
                else if (i == 2)
                {
                    if (Statics.IsLeapYear(year))
                    {
                        finalDate = new DateTime(year, i, 29);

                    }
                    else
                    {
                        finalDate = new DateTime(year, i, 28);
                    }
                }
                else
                {
                    finalDate = new DateTime(year, i, 30);
                }


                var lodgings = Statics.GetLodgings(context, initialDate, finalDate);
                lodgingsPerMonth[i] = lodgings.Count;                                       //

                dailyLodgingsPerMonth[i] = String.Format("{0:0.00}", ((float)lodgingsPerMonth[i] / (float)finalDate.Day));       //   Cambiado a string

                var doubleLodg = lodgings.FindAll(dl => dl.IsDouble == true);        //
                if (doubleLodg == null)
                {
                    doubleLodgingsPerMonth[i] = 0;
                }
                else { doubleLodgingsPerMonth[i] = doubleLodg.Count; }

                consumptionIncomePerMonth[i] = Statics.GetPurchasedProductsIncome(context, initialDate, finalDate);  //

                ConsumptionProfitPerMonth[i] = Statics.GetPurchasedProductsProfit(context, initialDate, finalDate);   //

                var employees = context.Employees.ToList();                        //
                foreach (Employee e in employees)
                {
                    salaryPerMonth[i] += Statics.GetEmployeeSalary(context, initialDate, finalDate, e.EmployeeId);
                }

                allHouseExpensesPerMonth[i] = Statics.GetMaintenanceExpenses(context, initialDate, finalDate) + Statics.GetHouseExpenses(context, initialDate, finalDate);    //

                rentIncomePerMonth[i] = (float)lodgings.Sum(l => l.RentCost);                  //

                damageIncomePerMonth[i] = Statics.GetIncomePerDamage(context, initialDate, finalDate);    //

                grossIncomePerMonth[i] = consumptionIncomePerMonth[i] + rentIncomePerMonth[i] + damageIncomePerMonth[i];    //

            }

            for (int i = 1; i < lodgingsPerMonth.Length; i++)
            {
                consumptionIncomePerMonthStr[i] = String.Format("{0:0.00}", consumptionIncomePerMonth[i]);
                ConsumptionProfitPerMonthStr[i] = String.Format("{0:0.00}", ConsumptionProfitPerMonth[i]);
                salaryPerMonthStr[i] = String.Format("{0:0.00}", salaryPerMonth[i]);
                allHouseExpensesPerMonthStr[i] = String.Format("{0:0.00}", allHouseExpensesPerMonth[i]);
                rentIncomePerMonthStr[i] = String.Format("{0:0.00}", rentIncomePerMonth[i]);
                damageIncomePerMonthStr[i] = String.Format("{0:0.00}", damageIncomePerMonth[i]);
                grossIncomePerMonthStr[i] = String.Format("{0:0.00}", grossIncomePerMonth[i]);

            }



            YearStatisticsViewModel ys = new YearStatisticsViewModel
            {
                Year = year,
                Months = new string[] { "", "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" },
                LodgingsPerMonth = lodgingsPerMonth,
                AnnualLodgings = lodgingsPerMonth.Sum(),
                DoubleLodgingsPerMonth = doubleLodgingsPerMonth,
                AnnualDoubleLodgings = doubleLodgingsPerMonth.Sum(),
                DailyLodgingsPerMonth = dailyLodgingsPerMonth,
                RentIncomePerMoth = rentIncomePerMonthStr,
                AnnualRentIncome = String.Format("{0:0.00}", rentIncomePerMonth.Sum()),
                ConsumptionIncomePerMonth = consumptionIncomePerMonthStr,
                AnnualConsumptionIncome = String.Format("{0:0.00}", consumptionIncomePerMonth.Sum()),
                ConsumptionProfitPerMonth = consumptionIncomePerMonthStr,
                AnnualConsumptionProfit = String.Format("{0:0.00}", ConsumptionProfitPerMonth.Sum()),
                DamageIncomePerMoth = damageIncomePerMonthStr,
                AnnualDamageIncome = String.Format("{0:0.00}", damageIncomePerMonth.Sum()),
                GrossIncomePerMonth = grossIncomePerMonthStr,
                AnnualGrossIncome = String.Format("{0:0.00}", grossIncomePerMonth.Sum()),

TrendyShop/Views/Statistics/Details.cshtml
@model TrendyShop.ViewModels.YearStatisticsViewModel
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<h1>@Model.Year</h1>



<table class="table-striped"  style="width:110%;">
    <tr>

        <th></th>
        <th>Reservas</th>
        <th>Reservas Dobles</th>
        <th>Reservas Diarias</th>
        <th>Ingreso x Renta</th>
        <th>Consumo</th>
        <th>Ganancia x Consumo</th>
        <th>Ingreso x daños</th>
        <th>Ingreso Bruto</th>
        <th>Salario</th>
        <th>Otros Gastos</th>
    </tr>


     @for (int i = 1; i <14 ; i++)
     {
<tr>
    @if (i != 13)
    {
        <td>@Model.Months[i]</td>
        <td>@Model.LodgingsPerMonth[i]</td>
        <td>@Model.DoubleLodgingsPerMonth[i]</td>
        <td>@Model.DailyLodgingsPerMonth[i]</td>
        <td>@Model.RentIncomePerMoth[i]</td>
        <td>@Model.ConsumptionIncomePerMonth[i]</td>
        <td>@Model.ConsumptionProfitPerMonth[i]</td>
        <td>@Model.DamageIncomePerMoth[i]</td>
        <td>@Model.GrossIncomePerMonth[i]</td>
        <td>@Model.SalaryPerMoth[i]</td>
        <td>@Model.HouseExpensesPerMoth[i]</td>
    }
    else { 
    <td></td>
    <td>@Model.AnnualLodgings</td>
    <td>@Model.AnnualDoubleLodgings</td>
    <td></td>
    <td>@Model.AnnualRentIncome</td>
    <td>@Model.AnnualConsumptionIncome</td>
    <td>@Model.AnnualConsumptionProfit</td>
    <td>@Model.AnnualDamageIncome</td>
    <td>@Model.AnnualGrossIncome</td>
    <td>@Model.AnnualSalary</td>
    <td>@Model.AnnualHouseExpenses</td>
    }
</tr>
     }

</table>
<br />

TrendyShop/Views/Statistics/Index.cshtml
@using TrendyShop.ViewModels
@{
    ViewData["Title"] = "Reservaciones";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model IEnumerable<YearStatisticsViewModel>


<script type="text/javascript">
    function togglezAppearance() {
        var dataDiv = document.getElementById("data-table");
        if (dataDiv.style.visibility == "hidden") {
            dataDiv.style.visibility = "visible";
        } else {
            dataDiv.style.visibility = "hidden";
        }
    }
</script>

<div class="col-lg-12 mx-auto">
    <div class="card">
        <div class="card-header">Estadísticas Anuales</div>
        <div class="card-body">
            @foreach (YearStatisticsViewModel ys in Model)
            {
                string collapseYear = '#' + @ys.Year.ToString();

                <div class="container">
                    <div class="panel-group" id="accordion">
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <h3 class="panel-title">
                                    <a data-toggle="collapse" data-parent="#accordion" href="@collapseYear">@ys.Year</a>
                                </h3>
                            </div>
                            <div id="@ys.Year.ToString()" class="panel-collapse collapse in">
                                <div class="panel-body">
                                    <table class="table table-bordered">
                                        <tr>

                                            <th></th>
                                            <th>Reservas</th>
                                            <th>Reservas Dobles</th>
                                            <th>Reservas Diarias</th>
                                            <th>Ingreso x Renta</th>
                                            <th>Consumo</th>
                                            <th>Ganancia x Consumo</th>
                                            <th>Ingreso x daños</th>
                                            <th>Ingreso Bruto</th>
                                            <th>Salario</th>
                                            <th>Otros Gastos</th>
                                        </tr>
                                        @for (int i = 1; i < 14; i++)
                                        {
                                            <tr>
                                                @if (i != 13)
                                                {
                                                    <td>@ys.Months[i]</td>
                                                    <td>@ys.LodgingsPerMonth[i]</td>
                                                    <td>@ys.DoubleLodgingsPerMonth[i]</td>
                                                    <td>@ys.DailyLodgingsPerMonth[i]</td>
                                                    <td>@ys.RentIncomePerMoth[i]</td>
                                                    <td>@ys.ConsumptionIncomePerMonth[i]</td>
                                                    <td>@ys.ConsumptionProfitPerMonth[i]</td>
                                                    <td>@ys.DamageIncomePerMoth[i]</td>
                                                    <td>@ys.GrossIncomePerMonth[i]</td>
                                                    <td>@ys.SalaryPerMoth[i]</td>
                                                    <td>@ys.HouseExpensesPerMoth[i]</td>
                                                }
                                                else
                                                {
                                                    <td>Total</td>
                                                    <td>@ys.AnnualLodgings</td>
                                                    <td>@ys.AnnualDoubleLodgings</td>
                                                    <td></td>
                                                    <td>@ys.AnnualRentIncome</td>
                                                    <td>@ys.AnnualConsumptionIncome</td>
                                                    <td>@ys.AnnualConsumptionProfit</td>
                                                    <td>@ys.AnnualDamageIncome</td>
                                                    <td>@ys.AnnualGrossIncome</td>
                                                    <td>@ys.AnnualSalary</td>
                                                    <td>@ys.AnnualHouseExpenses</td>
                                                }
                                            </tr>
                                        }
                                    </table>
                                    @*<div class="card-footer">
                                            @Html.ActionLink("Exportar a Excel", "ExportToExcel", "Statistics", new { yearS = ys})
                                        </div>*@
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
                @*<h3> @Html.ActionLink(year.ToString(), "Details", "Statistics", new { year })</h3>*@
            }
        </div>
        <div class="card-footer">
            <button onclick="location.pathname='/Home'">Cancelar</button>
        </div>
    </div>
</div>