TrendyShop/ViewModels/HouseExpensesViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TrendyShop.Models;

namespace TrendyShop.ViewModels
{
    public class HouseExpensesViewModel
    {
        public List<HouseExpense> LastExpenses { get; set; }
        public List<ExpenseType> ExpenseTypes { get; set; }
        public HouseExpense NewExpense { get; set; }
        public string DateFormat { get; set; }
    }
}

TrendyShop/Controllers/HouseExpensesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using TrendyShop.Data;
using TrendyShop.Models;
using TrendyShop.ViewModels;


namespace TrendyShop.Controllers
{
    [Authorize]
    public class HouseExpensesController : Controller
    {
        private DataContext context;
        public HouseExpensesController(DataContext ctx)
        {
            context = ctx;
        }
        public IActionResult Index()
        {
            var lastExpenses = new List<HouseExpense>
            {
              context.HouseExpenses.Include(h => h.ExpenseType).Where(h => h.ExpenseType.Name == "Electricidad").OrderByDescending(h => h.Date).FirstOrDefault(),
              context.HouseExpenses.Include(h => h.ExpenseType).Where(h => h.ExpenseType.Name == "Gas").OrderByDescending(h => h.Date).FirstOrDefault(),
              context.HouseExpenses.Include(h => h.ExpenseType).Where(h => h.ExpenseType.Name == "Lavandería").OrderByDescending(h => h.Date).FirstOrDefault(),
              context.HouseExpenses.Include(h => h.ExpenseType).Where(h => h.ExpenseType.Name == "Agua").OrderByDescending(h => h.Date).FirstOrDefault(),
            };

            var vm = new HouseExpensesViewModel
            {
                LastExpenses = lastExpenses,
                ExpenseTypes = context.ExpenseTypes.ToList(),
                DateFormat = DateTime.Today.ToString("yyyy-MM-dd")/* + "T" + DateTime.Today.ToString("hh:mm:ss")*/,
            };
            return View(vm);

        }

        [HttpPost]
        public IActionResult AddExpense(HouseExpense houseExpense)
        {
            //Si no es valido hay que avisar al usuario
            if (ModelState.IsValid)
            {
                houseExpense.ExpenseType = context.ExpenseTypes.Find(houseExpense.ExpenseTypeId);
                context.HouseExpenses.Add(houseExpense);
                context.SaveChanges();
            }
            return RedirectToAction("Index");
        }
        public IActionResult Delete(int heid)
        {
            var houseExpense = context.HouseExpenses.SingleOrDefault(c => c.Id == heid);
            context.Remove(houseExpense);
            context.SaveChanges();

            return RedirectToAction("Index");
        }
        public IActionResult Records(int eid, string expenseType)
        {
            List<HouseExpense> expenses = context.HouseExpenses.Where(e => e.ExpenseTypeId == eid && e.Date.Year == DateTime.Now.Year).ToList();

            return View(new Tuple<string, List<HouseExpense>>(expenseType, expenses));

        }
    }
}

TrendyShop/Views/HouseExpenses/Index.cshtml
@using TrendyShop.ViewModels
@model HouseExpensesViewModel
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="col-lg-8 mb-4 mx-auto">
    <div class="card ">
        <h2 class="card-header">
            Últimos pagos
        </h2>
        <div class="card-body">
            <table class="table table-bordered">
                <tr>
                    <th>Servicio</th>
                    <th>Fecha</th>
                    <th>Cantidad</th>
                    <th></th>
                    <th></th>
                </tr>
                @foreach (HouseExpense e in Model.LastExpenses)
                {
                    if (e != null)
                    {
                        <tr>
                            <td>@e.ExpenseType.Name</td>
                            <td>@e.Date.ToString("dd/MM/yy")</td>
                            <td>@e.Amount</td>
                            <td>@Html.ActionLink("", "Delete", "HouseExpenses", new { heid = e.Id }, new { @class = "fas fa-trash-alt" })</td>
                            <td>@Html.ActionLink("Registro", "Records", "HouseExpenses", new { eid = e.ExpenseTypeId, expenseType = e.ExpenseType.Name }, null)</td>
                        </tr>
                    }
                }
            </table>
        </div>
    </div>
</div>
<div class="col-lg-8 mb-4 mx-auto">
    <div class="card ">
        <h2 class="card-header">
            Nuevo Pago de Servicio
        </h2>
        <div class="card-body">
            @using (Html.BeginForm("AddExpense", "HouseExpenses"))
            {
                <div class="form-group">
                    <input type="number" step="any" name="Amount" placeholder="Ingrese cantidad" />

                    <select name="ExpenseTypeId" style="height: 27px">
                        @foreach (var item in Model.ExpenseTypes)
                        {
                            <option value="@item.ExpenseTypeId">@item.Name</option>
                        }
                    </select>

                    <label for="Date"></label>
                    <input type="date" step="any" name="Date" id="Date" value=@Model.DateFormat />


                </div>
                    <button type="submit">Guardar</button>
                    <button type="button" onclick="location.pathname='/Home'">Cancelar</button>
            }
        </div>
        
    </div>
</div>

TrendyShop/Views/HouseExpenses/Records.cshtml
@using TrendyShop.Models
@{
    ViewData["Title"] = "Registro de gastos";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model Tuple<string, List<HouseExpense>>



<div class="col-lg-8 mb-4 mx-auto">
    <div class="card ">
        <div class="card-header h-100">
            <h2>Registro de pagos de @Model.Item1</h2>
        </div>
        <div class="card-body">
            <table class="table table-bordered">
                <tr>
                    <th>Fecha</th>
                    <th>Cantidad</th>
                </tr>

                @foreach (var expense in Model.Item2)
                {
                    <tr>
                        <td>@expense.Date.ToString("dd/MM/yy")</td>
                        <td>@expense.Amount $</td>
                    </tr>
                }
            </table>
        </div>
        <div class="card-footer">
            <button onclick="location.pathname='/HouseExpenses'">Cancelar</button>
        </div>
    </div>
</div>