TrendyShop/ViewModels/StockViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TrendyShop.Models;

namespace TrendyShop.ViewModels
{
    public class StockViewModel
    {
        public List<Tuple<string, float,string,float>> Products { get; set; }
        public List<Lodging> Lodgins { get; set; }
        public float IncomePerRent { get; set; }
        public float IncomePerDamage { get; set; }
        public float ProductsIncome { get; set; }
        public float TotalIncome { get { return IncomePerRent + IncomePerDamage + ProductsIncome + MoneyOperationsIncome; } }
        public float LastFund { get; set;}
        public DateTime LastStockDate { get; set; }
        public float NewFund { get; set; }
        public float MoneyOperationsIncome { get; set; }
        public float TotalCash { get { return TotalIncome + LastFund; } }
        public bool IsPreviousStock { get; set; }
    }
}

TrendyShop/Controllers/StockController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using TrendyShop.Data;
using TrendyShop.Models;
using TrendyShop.Utility;
using TrendyShop.ViewModels;

namespace TrendyShop.Controllers
{
    [Authorize(Roles = SD.AdminEndUser)]
    public class StockController : Controller
    {
        private DataContext context;

        public StockController(DataContext ctx)
        {
            context = ctx;
        }
        public IActionResult Index(DateTime lastStockDate)
        {
            bool isPreviousStock = lastStockDate != default ? true : false;

            var lastStock = Statics.GetLastStock(context, default, lastStockDate);

            var vm = new StockViewModel
            {
                Lodgins = Statics.GetLodgings(context, lastStock.Date).OrderByDescending(l => l.LodgingNumber).ToList(),
                IncomePerRent = Statics.GetIncomePerRent(context, lastStock.Date),
                IncomePerDamage = Statics.GetIncomePerDamage(context, lastStock.Date),
                Products = Statics.GetIncomePerProduct(context, lastStock.Date),
                ProductsIncome = Statics.GetPurchasedProductsIncome(context, lastStock.Date),
                LastFund = lastStock.Fund,
                LastStockDate = lastStock.Date,
                MoneyOperationsIncome = Statics.GetMoneyOperationsIncome(context, lastStock.Date),
                IsPreviousStock = isPreviousStock
            };
            return View(vm);
        }

        public IActionResult Save(float fund)
        {
            context.Stocks.Add(
                new StockTaking
                {
                    Date = DateTime.Now,
                    Fund = fund
                }
                );
            context.SaveChanges();
            return RedirectToAction("Index", "Home");
        }

        public IActionResult PreviousStocks()
        {
            var result = context.Stocks.ToList();
            return View(result);
        }
    }
}

TrendyShop/Views/Stock/Index.cshtml
@using TrendyShop.ViewModels
@model StockViewModel
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<head>
    <style>
        input {
            width: 10%;
            border-color: grey;
            border-width: thin;
            border-radius: 2px
        }
    </style>
</head>
<div class=" col-lg-10 mx-auto">
    <div class="card">
        <div class="card-body">
            <table class="table table-bordered mb-3">
                <tr>
                    <th>Reservaciones</th>
                    <th>Cliente</th>
                    <th>Precio Extra</th>
                    <th>Renta</th>
                    <th>Consumo</th>
                    <th>Total</th>
                </tr>
                @foreach (var lodging in Model.Lodgins)
                {
                    var str = "#" + lodging.LodgingNumber.ToString() + " " + lodging.Date.ToString("hh:mm tt") + "-" + @lodging.FinalDate.ToString("hh:mm tt");
                    <tr>
                        <td>
                            @Html.ActionLink(str, "Details", "Lodging", new { roomId = lodging.RoomId, _date = lodging.Date })
                        </td>
                        <td class="text-right">@lodging.Customer.Name </td>
                        <td class="text-right">@lodging.ExtraCharge $</td>
                        <td class="text-right">@lodging.RentCost $</td>
                        <td class="text-right">@lodging.Consumption $</td>
                        <td class="text-right">@lodging.TotalPrice $</td>
                    </tr>
                }
                <tr>
                    <td style="background-color: rgb(116,216,216)">
                        <div class="d-flex">
                            <h5 class="mb-0"> Total de reservas:</h5> <h5 class="mb-0 ml-auto">@Model.Lodgins.Count</h5>
                        </div>
                    </td>
                    <td></td>
                    <td style="background-color: rgb(116,216,216)">
                        <div class="d-flex">
                            <h5 class="mb-0">Total:</h5> <h5 class="mb-0 ml-auto">@Model.IncomePerDamage $</h5>
                        </div>
                    </td>
                    <td style="background-color: rgb(116,216,216)">
                        <div class="d-flex">
                            <h5 class="mb-0">Total:</h5> <h5 class="mb-0 ml-auto">@Model.IncomePerRent $</h5>
                        </div>
                    </td>
                    <td style="background-color: rgb(116,216,216)">
                        <div class="d-flex">
                            <h5 class="mb-0">Total:</h5> <h5 class="mb-0 ml-auto">@Model.ProductsIncome $</h5>
                        </div>
                    </td>
                    <td style="background-color: rgb(116,216,216)">
                        <div class="d-flex">
                            <h5 class="mb-0">Total:</h5> <h5 class="mb-0 ml-auto">@Model.TotalIncome $</h5>
                        </div>
                    </td>
                </tr>
            </table>

            <table class="table table-bordered mb-3">
                <tr>
                    <th>Producto</th>
                    <th>Cantidad</th>
                    <th>Formula</th>
                    <th>Consumo</th>
                </tr>
                @foreach (var p in Model.Products)
                {
                    <tr>
                        <td>@p.Item1</td>
                        <td class="text-right">@p.Item2</td>
                        <td class="text-right">@p.Item3</td>
                        <td class="text-right">@p.Item4 $</td>
                    </tr>
                }
                <tr>
                    <td style="border:none"></td>
                    <td style="border:none"></td>
                    <td style="border:none"></td>
                    <td style="border:none; background-color: rgb(116,216,216)">
                        <div class="d-flex">
                            <h5 class="mb-0">Total: </h5>
                            <h5 class="mb-0 ml-auto">@Model.ProductsIncome $</h5>
                        </div>
                    </td>
                </tr>
            </table>
            <div class="d-flex">
                <h5 class="mb-0">Ingreso Total: @Model.TotalIncome $</h5>
                <h5 class="ml-4">Fondo anterior: @Model.LastFund $</h5>
                <h5 class="ml-4">Total en caja: @Model.TotalCash $</h5>
            </div>
            @if (Model.IsPreviousStock)
            {
                <button type="button" onclick="location.pathname='/Stock/PreviousStocks'">Atrás</button>
            }
            else
            {
                <form asp-action="Save" asp-controller="Stock">
                    <h5>Nuevo Fondo: <input id="newFund" type="number" step="any" name="fund" value="@Model.NewFund" /></h5>
                    <button type="submit">Guardar</button>
                    <button type="button" onclick="location.pathname='/Home'">Cancelar</button>
                </form>
            }
        </div>
    </div>
</div>
<script>
    document.getElementById("newFund").select();
</script>